name: inventario_app
description: App Flutter para consulta de inventario y compras
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ftpconnect: ^2.0.10
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  csv: ^6.0.0
  mobile_scanner: ^5.1.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
