name: inventario_app
description: App Flutter para consulta de inventario y compras
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ftpconnect: ^2.0.10
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  csv: ^6.0.0
  mobile_scanner: ^5.1.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuración de ícono (usando JPEG)
flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: assets/icon.jpeg                # icono base (JPEG)
  adaptive_icon_background: "#000000"         # color de fondo (ajústalo al de tu logo)
  adaptive_icon_foreground: assets/icon.jpeg  # mismo JPEG como frente (sin transparencia)
  # Opcional Android 13:
  # adaptive_icon_monochrome: assets/icon.jpg
